model_name: "bert-base-uncased"
data_dir: "data/SA"
output_dir: "outputs"
batch_size: 16 # giữ nguyên 
learning_rate: 5e-5 # giữ nguyên
epochs: 3         # giữ nguyên
eval_steps: 500
logging_steps: 10
